name: Packages build and publish to NuGet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack Psi
      run: dotnet pack src/Psi/Psi.csproj --output nuget-packages --configuration Release
    - name: Pack Psi.Codec.MessagePack
      run: dotnet pack src/Psi.Codec.MessagePack/Psi.Codec.MessagePack.csproj --output nuget-packages --configuration Release
    - name: Pack Psi.Discovery.Consul
      run: dotnet pack src/Psi.Discovery.Consul/Psi.Discovery.Consul.csproj --output nuget-packages --configuration Release
    - name: Pack Psi.Protocol.Tcp
      run: dotnet pack src/Psi.Protocol.Tcp/Psi.Protocol.Tcp.csproj --output nuget-packages --configuration Release
    - name: Push to NuGet
      run: dotnet nuget push 'nuget-packages/*.nupkg' --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols true

